name: Sync Kaggle Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC

jobs:
  fetch-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Setup Kaggle credentials from separate secrets
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Validate kaggle.json (optional debug)
        run: jq . ~/.kaggle/kaggle.json

      - name: Pull Kaggle Notebook
        run: |
          mkdir -p kaggle_notebooks
          kaggle kernels pull nancyaparekh/learn-pytorch-with-me -p kaggle_notebooks --force

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add kaggle_notebooks
          git commit -m "Sync: Updated from Kaggle" || echo "No changes"
          git push
